openapi: 3.0.0
info:
  title: TODO APP
  description: TODO App API
  version: 0.1.9

servers:
  - url: https://todo-api-j0cv.onrender.com/api
    description: production server

  - url: http://localhost:3000/api
    description: local server

paths:
  /items:
    get:
      tags:
        - Todos
      responses:
        '200':
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /item:
    post:
      tags:
        - Todos
      requestBody:
        description: create todo
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                item:
                  type: string
                completed: 
                  type: boolean
                id:
                  type: number
            example:
              item: Do chores
              completed: true
              id: 2
      responses:
        '200':
          description: todo created

  /categories:
    get:
      tags:
        - Categories
      responses:
        '200':
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /item/{id}:
    delete:
      tags:
        - Delete
      summary: Delete a ToDo item.
      description: Deletes the ToDo item with the specified ID from the database.
      parameters:
        - name: id
          in: query
          description: The ID of the ToDo item to delete.
          schema:
            type: integer
            format: int64
          required: true
      responses:
        '200':
          description: todo deleted
    put:
      tags:
        - Toggle
      summary: Update a ToDo item.
      description: Updates the `done` status of the ToDo item with the specified ID. The request body should include a `done` field with a boolean value indicating whether the task is completed or not.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                item:
                  type: string
                completed: 
                  type: boolean
                id:
                  type: number
      responses:
        '200':
          description: todo updated