openapi: 3.0.0
info:
  title: TODO APP
  description: TODO App API
  version: 0.1.9

servers:
  - url: https://todo-api-j0cv.onrender.com
    description: production server

  - url: http://localhost:3000/api
    description: local server

paths:
  /items:
    get:
      tags:
        - Todos
      responses:
        '200':
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /item:
    post:
      tags:
        - Todos
      requestBody:
        description: create todo
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                item:
                  type: string
                completed: 
                  type: string
                id:
                  type: number
            example:
              item: Do chores
              completed: true
              id: 2
      responses:
        '200':
          description: todo created

  /categories:
    get:
      tags:
        - Categories
      responses:
        '200':
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string